language: python

python:
  - "3.6"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U xmltodict
  - pip install -U black
  - pip install -U responses

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: run unit tests
      python: 3.6
      script: pytest
    - stage: test black code formatting
      python: 3.6
      script: black --check nxos-health-check/